spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: q1w2e3r4
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rebbitmp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
env:
  test7

girl:
  name: lili
  age: 254
